name: Component accessibility deliverables
description: Submit the accessibility portion of your component
title: '[Component name] component – accessibility '
type: 'task'
labels: ['accessibility', 'status: needs triage 🕵️‍♀️']
projects: ['carbon-design-system/39']
body:
  - type: markdown
    attributes:
      value: |
        Complete the following deliverables for Carbon to review the accessibility portion of the [component contribution process](https://carbondesignsystem.com/contributing/component/). To see examples, view the component accessibility guidelines on [GitHub](https://github.com/carbon-design-system/carbon/wiki/Component-Accessibility-Guidelines) or on [figma](https://www.figma.com/file/PmSOwLS3ldpSQtUf4xlaLD/component-accessibility-guidelines?type=design&node-id=434-4103&mode=design&t=qQ2DqDAiNaOLPlBC-0).

        1. Define component
        2. Document keyboard interactions
        3. Provide visual states
        4. Repeat steps 2 – 3 for each variant, if any
        5. Repeat step 3 for each child/subcomponent, if any

  - type: markdown
    attributes:
      value: '## 1. Define component'

  - type: checkboxes
    id: type
    attributes:
      label: Component type
      description:
        variants are only when the interaction differs from default component,
        not when there are only visual differences
      options:
        - label: Variant of existing component
        - label: New component with no variants
        - label: New component with variants
          required: false

  - type: checkboxes
    id: subcomponent
    attributes:
      label: Can it be opened/expanded to reveal a child/subcomponent?
      description:
        if the child/subcomponent is non-interactive, visual states may not be
        needed
      options:
        - label: Yes, it can
        - label: No, it cannot
          required: false

  - type: markdown
    attributes:
      value: '## 2. Document keyboard interactions'

  - type: checkboxes
    id: keyboard
    attributes:
      label: Select all that apply
      description:
      options:
        - label: '"Tab" moves between interactive components'
        - label: Arrow keys move between component and subcomponent
        - label: '"Enter" activates'
        - label: '"Space" selects'
        - label: '"Esc" closes'
          required: false

  - type: textarea
    id: visual-examples
    attributes:
      label: Create keyboard interaction visual examples
      description:
        'Provide screenshots or a figma link. In the early stages of
        contribution, only low fidelity visuals are required, but high fidelity
        visuals should be created by the time the component is ready to be
        published. Duplicate the [figma
        file](https://www.figma.com/file/PmSOwLS3ldpSQtUf4xlaLD/lo-fi-keyboard-interaction-visual?type=design&node-id=434-4103&t=kO1MZkuNTKMIAj0h-0)
        to see examples and use the provided assets.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: '## 3. Provide visual states'
  - type: textarea
    id: visual-states
    attributes:
      label:
        Focused and non-focused states for default, selected, error (if any) and
        error + selected (if any)
      description:
        'Provide screenshots or a figma link. This is in addition to what Carbon
        may require. Duplicate the [figma
        file](https://www.figma.com/file/PmSOwLS3ldpSQtUf4xlaLD/lo-fi-keyboard-interaction-visual?type=design&node-id=434-4103&t=kO1MZkuNTKMIAj0h-0)
        to see examples and use the provided template.'
    validations:
      required: true
