name: Documentation issue 📖
description:
  Report missing, incorrect, or otherwise inconsistent documentation here.
title: '[Docs]: '
labels: 'type: bug 🐛'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to fill out this form that will help us make
        more clear documention.

  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Where is the problem you're identifying in the documentation?
      multiple: false
      options:
        - https://www.carbondesignsystem.com
        - https://react.carbondesignsystem.com
        - https://github.com/carbon-design-system/carbon/tree/main/docs
    validations:
      required: true

  - type: input
    id: section
    attributes:
      label: Section
      description:
        'Which page are you experiencing the problem with the documentation?'
      placeholder: https://carbondesignsystem.com/components/accordion/usage/
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description:
        'Describe the problem you’re experiencing in the documentation. Please
        attach any screen shots or videos to illustrate the problem.'
      placeholder:
        The abc component is missing usage instructions about the xyz prop.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description:
        'What would you expect to see instead? Please attach any screen shots or
        videos to illustrate a possible solution.'
      placeholder: _Your amazing idea here_

  - type: dropdown
    id: severity
    attributes:
      label: Suggested Severity
      description:
        'Read more to understand our [severity
        levels](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/support.md#severity)'
      options:
        - 'Severity 1 = The documentation damages the brand or exposes
          intellectual property.'
        - 'Severity 2 = The documentation is wrong or missing major details. It
          conflicts with what we are saying in another part of the system.	'
        - "Severity 3 = The documentation is mis-leading, somewhat true, missing
          minor details, or grammatically incorrect. It doesn't present
          conflicts with other parts of the design system."
        - 'Severity 4 = Unrelated to a user task. Content has a typo.'

  - type: input
    id: application
    attributes:
      label: Application
      description: 'What application do you work on?'

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
          required: true
        - label:
            I checked the [current
            issues](https://github.com/carbon-design-system/carbon/issues) for
            duplicate problems
