name: Add To Project

on:
  issues:
    types: [opened, labeled]

jobs:
  issue-triage:
    uses: carbon-design-system/carbon/.github/workflows/add-to-project.yml@main
    secrets:
      ADD_TO_PROJECT_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}
