name: Sync content with platform

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.mdx'

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: carbon-design-system/carbon-platform
          ref: main
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create issue on platform repo
        run: |
          gh issue create --title "[Content sync]: carbon-website" --label "role: dev 🤖" --label "service: web-app 🌎" --body 'A pull request on carbon-website was just merged. It contains .mdx content changes that may need to be synced to platform:
          - ${{ github.event.compare }}'
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
